---
title: "Chemtax Analysis"
author: "Anna Finch"
date: '2022-06-24'
output: html_document
---

# Load libraries
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
librarian::shelf(
    librarian, ggplot2, tibble, tidyr, readr, purrr, dplyr, stringr,
    forcats, lubridate, glue, fs, magrittr, here,
    # broom # optional
    
    # additional
    rstatix, readxl
    )

library("conflicted")

conflict_prefer("filter", "dplyr")
conflict_prefer("select", "dplyr")
```

# Load Average Phytoplankton Concentrations from CHEMTAX 
```{r load-avg-phyto-data}
file.chem <-
  fs::dir_ls(path    = here("data", "raw"),
             recurse = TRUE,
             regexp  = "mbonpig.*\\.xls$") %>% 
  str_sort() %>%
  tibble(files = .)
  
cmtx_all <- 
    file.chem %>%
    filter(str_detect(files, "cluster")) %>%
    mutate(
      filename = basename(files) %>% tools::file_path_sans_ext(),
      ranges   = c("D177:N178", "D273:N274", "D241:N242", "D305:N306"),
      cluster  = str_trunc(filename, 1, "left", ellipsis = ""),
      season   = fct_inorder(c("Winter", "Spring", "Summer", "Autumn")),
      data     = map2(files, ranges, 
                      ~ read_xls(
                          path = .x,
                          sheet = 2,
                          range = .y,
                          .name_repair = janitor::make_clean_names
                          ))
      ) %>%
  select(-c(1:ranges))  %>%
  unnest(data)
```

```{r names-for-plts}
phyto_name <- 
    tibble(
        names = c("Chlorophytes", "Cryptophytes", "Cyanobacteria 2", 
                  "Cyanobacteria 4", "Diatoms 1", "Diatoms 2", 
                  "Dinoflagellates", "Haptophytes 6","Haptophytes 8", 
                  "Prasinophytes")
        )

phyto_shrt <- names(cmtx_all)[-c(1:3)]
```


# ---- Line Plot ----
```{r line-plt}
plot_pig <- function(.dat, .var, .title) {
    
    # set limits
    ylims <- c(0, max(.dat[[.var]]) * 1.05)
    brake <- pretty(ylims, 5)
    
    # plot
    .dat %>%
    ggplot(aes_string(x = "season", y = .var)) +
    geom_point(size = 2) +
    geom_line(group = 1, 
              size  = 1) +
    
    # labels
    labs(title = glue("Average Concentration per Season of {.title}"),
         x     = "Season",
         y     = expression(paste("Concentration (mg ", m^-3, ")"))) +
     
    # scale setup   
    scale_y_continuous(breaks = brake,
                       limits = ylims,
                       expand = expand_scale(mult = c(0, 0))
                       ) +
    
    # theme setup   
    theme_bw(base_family = "serif") +
    theme(
      panel.grid.major.y = element_blank(),
      panel.grid.minor.y = element_blank(),
      plot.title         = element_text(size = 15),
      axis.ticks.length  = unit(-0.05, "in"),
      axis.text.y       = element_text(margin = unit(c(0.3,0.3,0.3,0.3), "cm")),
      axis.text.x       = element_text(margin = unit(c(0.3,0.3,0.3,0.3), "cm")),
      axis.ticks.x      = element_blank(),
      legend.background = element_rect(color = "black", fill = "white")
    )
}

# ---- avg season line plots ----
temp1 <- cmtx_all %>%
    select(-rms) %>%
    pivot_longer(
                 cols = -c(1:2),
                 names_to = "phyto",
                 values_to = "avg_conc"
    )  %>%
    group_by(phyto) %>%
    nest() %>%
    bind_cols(phyto_name) %>%
    mutate(
        plt = map2(data, names, ~ plot_pig(.dat = .x, 
                                           .var = "avg_conc", 
                                           .title = .y))
    )

temp1$plt
```

# Load All Phytoplankton Concentrations
```{r load-comb-data}
cmtx_avgs_raw <- 
    pull(file.chem, files)[5] %>%
    readxl::read_xls(.,
                     sheet = 1,
                     .name_repair = janitor::make_clean_names
                     )

meta_data <-
    here("data", "processed", "combined_pig_dat.csv") %>%
    read.csv() %>% 
    select(
        hplc_gsfc_id:filter_storage_before_shipment_to_gfsc,
        comments, season
        ) %>%
    filter(name_of_water_body == "Florida Keys") %>%
    mutate(
        season = fct_inorder(season),
        season = fct_relabel(season, ~ c("Winter", 
                                         "Spring", 
                                         "Summer", 
                                         "Autumn"))
    )
    
cmtx_avgs <-
    full_join(meta_data, cmtx_avgs_raw, by = c("sample" = "sample_id"))

if (!fs::file_exists(here("data", "processed", "chemtax_with_metadata.csv"))) {
    
    write_csv(cmtx_avgs, 
              here("data", "processed", "chemtax_with_metadata.csv"))
}
```


# ---- Box Plots ----
```{r boxplots}
box_plt <- function(.dat, .var, .title) {
    
    # limits for plot
    ylims <-  c(0, quantile(.dat[[.var]], 0.99))
    brake <- pretty(ylims, 6)

    # plotting
    .dat %>%
    ggplot() +
    geom_boxplot(
                 aes_string(x = "season", y = .var),
                 outlier.shape = NA) +
    geom_jitter(
            aes_string(x = "season", y = .var, color = "year"),
            width = 0.4,
            size = 0.5
        ) +
    
    # labels
    labs(title = glue("Concentration of {.title} per Season "),
         x     = "Season",
         y     = expression(paste("Concentration (mg", m^-3, ")")),
         color = "Year") +

    # scale settings
    scale_color_binned(type = "viridis") +
    
    scale_y_continuous(breaks = brake,
                       expand = expand_scale(mult = c(0, 0)),
                       oob = scales::squish,
                       limits = ylims
                       ) +
    
    # theme settings
    theme_bw(base_family = "serif") +
    theme(
      panel.grid        = element_blank(),
      plot.title        = element_text(size = 15),
      axis.ticks.length = unit(-0.05, "in"),
      axis.text.y       = element_text(margin = unit(c(0.3,0.3,0.3,0.3), "cm")),
      axis.text.x       = element_text(margin = unit(c(0.3,0.3,0.3,0.3), "cm")),
      axis.ticks.x      = element_blank(),
      legend.background = element_rect(color = "black", fill = "white")
    )
}

# ---- avg season line plots ----
temp2 <-
    cmtx_avgs %>%
    select(-c(pi:volfilt, bottle, filter_type:comments)) %>%
    pivot_longer(
                 cols = chloro:pras,
                 names_to = "phyto",
                 values_to = "avg_conc"
    )  %>%
    group_by(phyto) %>%
    nest() %>%
    bind_cols(phyto_name) %>%
    mutate(
        plt = map2(data, names, ~ box_plt(.dat = .x, 
                                           .var = "avg_conc", 
                                           .title = .y))
    )

temp2$plt
```
```{r}
#PFTs with larger scales 
cmtx_longer %>% 
    filter(!func_type %in% c("chloro", "crypto", "diat1", "diat2", "dino", "pras")) %>% 
    ggplot(aes(x=season, y = value, fill = season)) +
    geom_boxplot(outlier.shape = NA) +
    facet_wrap(facet =~ func_type, ncol = 2) +
    theme_classic() +
    theme(text = element_text(family = "serif", size = 18),
          axis.text = element_text(size = 10),
          legend.position = "none") +
    scale_y_continuous(expand = c(0,0), limits = c(0, 0.2)) +
    labs(x = "Season",
         y = expression(paste("Concentration of Chlorophyll-a (mg  ", m^-3, ")")))

save_plot(
    filename    = here("data", "plots", 
                    glue("cmtx_boxplots_large", 
                         format(Sys.time(), '_%Y%m%d_%H%M%S'),
                          ".jpg")), 
    plot        = last_plot(),
    base_height = 5,
    base_width  = 15,
    dpi         = 600, 
    units       = "in", 
    device      = "png")

#plot for PFTs with smaller scales
cmtx_longer %>% 
    filter(func_type %in% c("cyano2", "chloro", "hapt6")) %>% 
    ggplot(aes(x=season, y = value, fill = season)) +
    geom_boxplot(outlier.shape = NA) +
    facet_wrap(facet =~ func_type, ncol = 3) +
    theme_classic() +
    theme(text = element_text(family = "serif", size = 30),
          axis.text = element_text(size = 12),
          legend.position = "none") +
    scale_y_continuous(expand = c(0,0), limits = c(0, 0.2)) +
    labs(x = "Season",
         y = expression(paste("Concentration of Chlorophyll-a (mg  ", m^-3, ")")))

identical(fs::dir_ls(here("data", "plots"),
           regexp = "cmtx_boxplots", 
           recurse = TRUE)  %>%
           as.character(), character(0))


if (FALSE) {
    cowplot::save_plot(
        filename    = here("data", "plots", "boxplots",
                           glue(
                               "cmtx_boxplot",
                               format(Sys.time(), '_%Y%m%d_%H%M%S'),
                               ".jpg"
                           )),
        plot        = last_plot(),
        base_height = 8,
        base_width  = 16,
        dpi         = 600,
        units       = "in",
        device      = "png"
    )
    }
```

```{r ANOVA}
# #ANOVA test
# summary(aov(diat2 ~ season, data=cmtx_avgs))
# 
# #Dunn test with Bonferroni correction
# chloro_dunn <- dunn_test(cmtx_avgs, chloro ~ season, p.adjust.method = "bonferroni")
# crypto_dunn <- dunn_test(cmtx_avgs, crypto ~ season, p.adjust.method = "bonferroni")
# cyano4_dunn <- dunn_test(cmtx_avgs, cyano4 ~ season, p.adjust.method = "bonferroni")
# dino_dunn <- dunn_test(cmtx_avgs, dino ~ season, p.adjust.method = "bonferroni")
# hapt6_dunn <- dunn_test(cmtx_avgs, hapt6 ~ season, p.adjust.method = "bonferroni")
# hapt8_dunn <- dunn_test(cmtx_avgs, hapt8 ~ season, p.adjust.method = "bonferroni")
# pras_dunn <- dunn_test(cmtx_avgs, pras ~ season, p.adjust.method = "bonferroni")

```

```{r kruskal-and-dunn}
cmtx_longer <- cmtx_avgs %>% 
    pivot_longer(cols = chloro:pras, names_to = "func_type", values_to = "value")

cmtx_kruskal <- cmtx_longer %>% 
    group_by(func_type) %>% 
    kruskal_test(value ~ season)

cmtx_dunn <- cmtx_longer %>%
    filter(!(func_type %in% c("cyano2", "diat1"))) %>% 
    group_by(func_type) %>%
    dunn_test(value ~ season, p.adjust.method = "bonferroni")

```

```{r station-seasonally-yearly-avgs}
cmtx_stat <- cmtx_avgs %>% 
    mutate(diat = diat1 + diat2,
           cyano = cyano2 + cyano4,
           hapt = hapt6 + hapt8,
           total = chloro + crypto + diat + dino + hapt + pras + cyano
           ) %>% 
    # group_by(year, season, station) %>% 
    group_by(season) %>% 
    summarise_at(vars(chloro:hapt),
                 list(avg = mean, sd = sd, var = var),
                 na.rm = TRUE)
options(scipen = 999)

cmtx_fract <- cmtx_avgs %>% 
    mutate(diat = diat1 + diat2,
           cyano = cyano2 + cyano4,
           hapt = hapt6 + hapt8,
           total = chloro + crypto + diat + dino + hapt + pras + cyano) %>% 
    mutate(year = year,
              season = season,
              station = station,
              frac_chloro = chloro/total,
           frac_crypto = crypto/total,
           frac_cyano = cyano/total,
           frac_diat = diat/total,
           frac_dino = dino/total,
           frac_hapt = hapt/total,
           frac_pras = pras/total) %>% 
    select(hplc_gsfc_id:season, frac_chloro:frac_pras)



cmtx_fract %>% 
    pivot_longer(frac_chloro:frac_pras, names_to = "func_type", values_to = "frac", names_prefix = "frac_") %>% 
    filter(func_type %in% c("diat", "cyano")) %>% 
    filter(station %in% c("WS", "10", "16")) %>% 
ggplot(aes(x=lubridate::ymd_hms(date_time_utc), y = frac, color = func_type, fill = func_type))+
    geom_point() +
    geom_line() +
    facet_wrap(facets = "station") +
    theme_classic() +
    theme(text = element_text(family = "serif", size = 40),
          axis.text = element_text(size = 30),
          legend.position = c(0.5, 0.8)) +
    labs(x     = NULL, 
         y     = "Proportion to Total Chl-a",
         color = "Functional Type", 
         fill  = "Functional Type"
         )

cowplot::save_plot(
    filename    = here("data", "plots", glue("phyto_bloom", ".jpg")), 
    plot        = last_plot(),
    base_height = 8,
    base_width  = 16,
    dpi         = 600, 
    units       = "in", 
    device      = "png")


view(cmtx_fract %>% 
         group_by(season) %>% 
         summarise_at(vars(frac_chloro:frac_pras), list(avg = mean)))
view(cmtx_fract %>% 
         mutate(station = forcats::fct_reorder(station, lon)) %>% 
         group_by(station) %>% 
         summarise_at(vars(frac_chloro:frac_pras), list(avg = mean)))




max_fract <- cmtx_fract %>%
    group_by(hplc_gsfc_id) %>% 
    summarise(max_frac = max(frac)) %>% 
    left_join(cmtx_fract, by = c("max_frac" = "frac"))

cmtx_fract2 <- 
    cmtx_fract %>%
    group_by(season) %>%
    summarise_at(vars(frac_chloro:frac_pras), 
                 list(avg = mean)) %>%
    
    pivot_longer(
        frac_chloro_avg:frac_pras_avg,
        names_to     = "func_type",
        names_prefix = "frac_",
        values_to    = "avg_fract"
    ) %>% 
    
    mutate( 
        func_type = gsub("_avg", "", func_type)
        ) %>% 
    
    ggplot(aes(
               fill  = func_type,
               color = func_type,
               y     = avg_fract,
               x     = season
    )) +
    geom_bar(position = "fill", 
             stat     = "identity") +
    
     labs(x     = "Season",
         y     = "Proportion to Total Chl-a",
         fill  = "Phytoplankton Functional Type",
         color = "Phytoplankton Functional Type") +
    
    scale_fill_manual(values  = Tol_muted) +
    scale_color_manual(values = Tol_muted) +
    
    # theme
    theme_classic() +
    theme(
        text             = element_text(family = "serif", size = 40),
        axis.title       = element_text(size = 40),
        legend.position  = "bottom",
        legend.direction = "horizontal"
    ) 
   

cowplot::save_plot(
    filename    = here("data", "plots", 
                       glue("phyto_func_type_bar_ratio_reason", 
                       format(Sys.time(), '_%Y%m%d_%H%M%S'),
                       ".jpg")), 
    plot        = last_plot(),
    base_height = 8,
    base_width  = 16,
    dpi         = 600, 
    units       = "in", 
    device      = "png")

    # gt(
    #     rowname_col = NULL,
    #     groupname_col = NULL
    # ) %>% 
    # cols_label(
    #     frac_chloro_avg = "Chloro",
    #     frac_crypto_avg = "Crypto",
    #     frac_cyano_avg = "Cyano",
    #     frac_diat_avg = "Diat",
    #     frac_dino_avg = "Dino",
    #     frac_hapt_avg = "Hapt",
    #     frac_pras_avg = "Pras") %>% 
    # tab_options(
    #     table_body.hlines.width = 0,
    #     table_body.vlines.width = 0,
    #     stub.border.width = 0
    # ) %>%
    # # fmt_number(columns = starts_with("frac"), decimals = 4) %>% 
    # fmt_percent(columns = starts_with("frac"), decimals = 0) %>% 
    # tab_spanner(label = "Average Fraction",
    #             columns = frac_chloro_avg:frac_pras_avg) %>% 
    # tab_stubhead("Season") %>% 
    # opt_table_font("serif") %>% 
    # gtsave(filename = here("data", "plots", glue("community_fractions", 
    #        format(Sys.time(), '_%Y%m%d_%H%M%S'),
    #        ".html")))

```

