---
title: "HPLC Microscopy Match-up"
author: "Sebastian DiGeronimo"
date: '2022-06-30'
output: html_document
---

```{r setup, include=FALSE}
librarian::shelf(
    librarian, ggplot2, tibble, tidyr, readr, purrr, dplyr, stringr,
    forcats, lubridate, glue, fs, magrittr, here,
    # broom # optional
    
    # additional
    blandr
)

library("conflicted")

conflict_prefer("filter", "dplyr")
conflict_prefer("select", "dplyr")
```
# ---- Load data ----
```{r pigments}
df_pig <-
here("data","processed", "combined_pig_dat.csv") %>%
    readr::read_csv(.,
                    show_col_types = FALSE) %>%
    
    # fix wrong date
    mutate(
        date_time_utc = if_else(
            as_date(date_time_utc) == as_date("2018-01-08") &
                str_detect(station, "MR"), 
            ymd_hms("2018-01-09 00:52:00"),
            date_time_utc),
        date   = as_date(date_time_utc),
        .after = date_time_utc
        ) 
```

```{r microscopy}
df_micro <-
    fs::dir_ls(
        here("data", "raw"),
        regexp  = "Sample overview.+FWRI\\.xlsx$",
        recurse = TRUE
        ) %>%
    
    # read file
    readxl::read_excel(
        skip  = 2,
        sheet = 2,
        .name_repair = janitor::make_clean_names
    ) %>%
    
    # filter rows for full counts only
    filter(str_detect(count_details, "Full.*")) %>%
    
    rename(lat = latitude,
           lon = longitude) %>%
    
    # fix date and make datetime column
    mutate(
        sample_time = hms::as_hms(sample_time),
        date_time   = sample_date + sample_time,
        .before     = time_zone
    ) %>%
    
    # removes rows without station IDs
    filter(!is.na(station_id)) %>%
    
    # extracts station #, removing 
   mutate(station = str_remove(station_id, "^(Keys MBON |NOAA-AOML )"),
          station = str_replace_all(station, "/|\\s", "_"),
          station = str_replace(station, "21_LK", "LK"),
           .after = station_id 
    ) %>%
    
    # replaces NA values to 0 for count data
    mutate(across(achnanthes_sp:last_col(), ~ replace_na(., 0)))
```

```{r create-index-merge}
# create columns for surface and depth
sm_mic <- 
    df_micro %>%
    rename(depth = sample_depth_m) %>%
    select(habid, date = sample_date, date_time, station, depth)  %>%
    group_by(station, date_time) %>%
    mutate(depth_id = case_when(
        n() > 1 & depth == min(depth) ~ "SUR",
        n() > 1 & depth == max(depth) ~ "BOT",
        depth > 5 ~ "BOT",
        TRUE      ~ "SUR"
    )) %>%
       ungroup()

sm_pig <- 
    df_pig %>%
    select(sample, date,  date_time_utc, station, depth) %>%
    
    # filters duplicates at same depth
    distinct(station, date_time_utc, depth, .keep_all = TRUE) %>%

    group_by(station, date_time_utc) %>%
    
    mutate(depth_id = case_when(
        n() > 1 & depth  == min(depth) ~ "SUR",
        n() > 1 & depth > min(depth)   ~ "BOT",
        depth > 5 ~ "BOT",
        TRUE      ~ "SUR"
    )) %>%
    ungroup()

# index to be added to each dataframe to reference later
indx_match <-
    inner_join(sm_pig, sm_mic, 
               by = c("station", "date", "depth_id")) %>%
    select(sample, habid) %>%
    mutate(
        indx = glue("{row_number()}-{str_remove(sample, '.*(_|-)')}")
    )


df_micro_filt <-
    df_micro %>%
    filter(habid %in% indx_match$habid) %>%
    mutate(indx = indx_match$indx, .before = 1)

df_pig_filt <-
    df_pig %>%
    filter(sample %in% indx_match$sample) %>%
    mutate(indx = indx_match$indx, .before = 1)

rm(df_micro, df_pig, sm_pig, sm_mic)
```

# Group micro and pigments
```{r match-taxa-obis}
# ---- load taxa list ----
taxa_df <-
     fs::dir_ls(
        here("data", "raw"),
        regexp  = "Sample overview.+FWRI\\.xlsx$",
        recurse = TRUE
        ) %>%
    readxl::read_xlsx(
        path  = .,
        sheet = 3,
        skip  = 1
        ) %>% 
    na.omit() %>% 
    rename(taxa = 1) %>%
    mutate(
        taxa_fix = str_replace(taxa, "(?i)Pseudo.*chia","Pseudonitzschia"),
        genus    = stringr::str_split(taxa_fix, "_", 2, simplify = TRUE)[,1],
        species  = stringr::str_split(taxa_fix, "_", 2, simplify = TRUE)[,2]
    ) %>%
     filter(!str_detect(genus, 
                        glue("Copepods|Detritus|Zooplankton|Foraminifera|",
                             "Globigerinidae|Nauplii|Choanoflagellate")
                          ))

# ---- search obis for taxa id names ----
# Prompts:
# cilates - 3
# diatom - 1
# niscthiza - 1
taxa_id_all <- 
    taxa_df  %>% 
    distinct(genus) %$% 
    obistools::match_taxa(genus, ask = TRUE) %>%
    mutate(
        aphiaid = str_remove(scientificNameID, 
                           "urn:lsid:marinespecies.org:taxname:")
           ) %>% 
    as_tibble()

# filter out non-matched taxa
taxa_nt_mt <- 
    taxa_df %>% 
    distinct(genus) %>%
    bind_cols(taxa_id_all) %>% 
    filter(is.na(scientificName)) %>% 
    select(1)

# keep matched taxa and only aphia id
taxa_info <- 
    taxa_id_all %>% 
    distinct(aphiaid) %>% 
    drop_na() %>%
    mutate(temp = map(aphiaid, ~ robis::taxon(.x))) %>%
    unnest(temp)

taxa_info
```
# Categorize Taxa into functional types 
1. Make a list of genera/taxa for each PFT
2. Make new columns in `df_micro_filt` for each PFT by columns sum contributing 
   to the PFT
```{r pft-cat}
# PFT relating to scientific name, either by class level or genus level
# class
cat_class <- tribble(
    ~pft1,    ~sc_name,
    "diat",   "Bacillariophyceae", 
    "dino",   "Dinophyceae", 
    "cyano",  "Cyanophyceae", 
    "chloro", "Chlorophyceae", 
    "crypto", "Cryptophyceae", 
    "pras",   "Pyramimonadophyceae" 
)

# genus
cat_gen <- tribble(
    ~pft2,    ~sc_name,
    "chloro", "Chlorophyte", 
    "hapt",   "Coccolithophorid", 
    "dino",   "Dinocyst", 
    "dino",   "Dinoflagellate", 
    "dino",   "Warnowioid", 
    "dino",   "Gymnodinoid",
    "dino",   "Scrippsielloid",
    "dino",   "Polykrikoid",
    "diat",   "Microdiatoms", 
    "diat",   "Nanodiatoms",
    "diat",   "Nitzschioid", 
    "diat",   "Naviculoid",
    "diat",   "Diatom", 
    "diat",   "Pleurosigmataceae", 
    "diat",   "Pseudonitzschia", 
    "crypto", "Cryptomonad",
    "cyano",  "Cyanobacteria",
    "cyano",  "Johannebaptista",
    "cyano",  "Picoplankton"
)
```
```{r merge-cat}
# group scientific names to PFT
df_class <-   
    taxa_df %>%
    full_join(taxa_info, by = "genus") %>%

    # join by class 
    left_join(
        cat_class, by = c("class" = "sc_name")
    ) %>%
        
    # join by genus
    left_join(
        cat_gen, by = c("genus" = "sc_name")
    ) %>%
    unite("func_type", pft1, pft2, na.rm = TRUE) %>%
    
    drop_na(taxa_fix) %>% 
    mutate(taxa = str_to_lower(taxa)) %>%
    relocate(func_type, .after = taxa_fix)

# column name into taxa 
micro_longer <-
    df_micro_filt %>%
    pivot_longer(
        cols      = achnanthes_sp:last_col(),
        names_to  = "taxa",
        values_to = "count"
    ) %>%
    left_join(
        df_class %>% select(taxa,func_type), # filter out most columns
        by = "taxa")

```
```{r merge-micro-pigm}
cmtx_avgs_raw <- 
    fs::dir_ls(path  = here("data", "raw"),
             recurse = TRUE,
             regexp  = "mbonpig\\.xls$") %>%
    readxl::read_xls(
        .,
        sheet = 1,
        .name_repair = janitor::make_clean_names
        ) %>%
    
    # combine diat, cyano, hapt concentrations into main group
    mutate(diat  = diat1 + diat2,
           cyano = cyano2 + cyano4,
           hapt  = hapt6 + hapt8
           ) %>%
    pivot_longer(
                 cols = chloro:last_col(),
                 names_to = "taxa",
                 values_to = "conc"
    )
    
# these sample id won't exists in cmtx_avgs_raw becasuse not from FL Keys 
# c("WS16319_113", "WS18008_43",  "WS16130_142", "WS16130_148", "WS16263_83", "WS19119-79" )  

df_type_counts <-
    micro_longer %>%
    group_by(indx, func_type) %>%
    summarise(micro_count = sum(count)) %>% 
    ungroup() %>%
    left_join(select(indx_match, sample, indx), by = "indx") %>%
    left_join(cmtx_avgs_raw, 
              by = c("sample" = "sample_id", "func_type" = "taxa")) %>%
    filter(str_detect(func_type, "") & !is.na(conc))

 
    
df_pig_filt2 <-
    df_pig_filt  %>%
    select(
        indx, sample, date_time_utc:lat
    ) %>%
    
    # join chemtax and microscopy data
    right_join(df_type_counts, by = c("indx", "sample")) %>%

    # select desired columns
    select(indx, func_type, conc, micro_count) %>% 
    filter(conc >= 0 & micro_count >= 0) %>% 
        
    # not sure why filter this out
    filter(!str_detect(indx, "17-3|3-35|4-39"))

df_pig_filt2
```

# ---- Start Bland-Altman ----
```{r sub-sample}
set.seed(122237)
cf_avgs <-
    df_pig_filt2 %>%
     
    # group by func_type
    group_by(func_type) %>%
    
    filter(conc > 0 & micro_count > 0 ) %>%
        
    # sample subset of data to produce conversion factors
    slice_sample(prop = 0.5) %>%

    # calculate conversion factors
    mutate(cf = conc / micro_count) %>%
    
    # average the conversion factors
    summarize(avg_cf = mean(cf), med_cf = median(cf))

cmtx_micro <- 
    df_pig_filt2 %>% 
    left_join(cf_avgs, by = "func_type") %>%
    
    # not sure why we want to filter out the used data for this?
    # filter(!indx %in% rand_indx) %>% 
    
    # conversion factors * microscopy counts to get [chla] per PFT
    mutate(micro_conc     = micro_count * avg_cf,
           log_conc       = log(conc + 1e-6),
           log_micro_conc = log(micro_conc + 1e-6)
           ) #%>% 
    
    # pivot_wider(
    #     id_cols     = indx,
    #     names_from  = func_type,
    #     values_from = c(conc, micro_conc)
    # )

cmtx_micro_log <-
    df_pig_filt2 %>% 
    left_join(cf_avgs, by = "func_type") %>%
    
    # conversion factors * microscopy counts to get [chla] per PFT
    mutate(
        micro_conc   = micro_count * avg_cf,
        log_mic_conc = log(micro_conc + 1e-6),
        log_conc     = log(conc + 1e-6)
    ) # %>%
    
    # pivot_wider(
    #     id_cols     = indx,
    #     names_from  = func_type,
    #     values_from = c(log_conc, log_mic_conc)
    # )

```


```{r view-prop-vague-class}
# view(micro_longer %>% 
#     filter(!(taxa %in% c("copepods", "detritus", "zooplankton", "foraminifera_unidentified",
#                           "globigerinidae", "nauplii", "choanoflagellate",
#                          "strombidium_like", "vorticella_sp", "vorticella_spp"
#                           ))) %>% 
#     group_by(indx) %>% 
#     mutate(total = sum(count)) %>% 
#     filter(func_type == "other") %>% 
#     summarise(fraction_of_other = sum(count)/total) %>% 
#     dplyr::distinct(fraction_of_other))
# 
# vague <- c("ciliates", "flagellate_unidentified", "microflagellates", "nanoflagellates",
#           "nanoplankton", "other_plankton", "phytoplankton", "picoflagellates",
#           "picoplankton")
# 
# view(micro_longer %>% 
#     filter(!(taxa %in% c("copepods", "detritus", "zooplankton", "foraminifera_unidentified",
#                           "globigerinidae", "nauplii", "choanoflagellate",
#                          "strombidium_like", "vorticella_sp", "vorticella_spp"
#                           ))) %>% 
#     group_by(indx) %>% 
#     mutate(total = sum(count)) %>% 
#     filter(taxa %in% vague) %>% 
#     summarise(fraction_of_vague = sum(count)/total,
#               totals = sum(count)) %>% 
#     dplyr::distinct(fraction_of_vague,totals, fraction_of_vague))
# 
# view(micro_longer %>%
#     filter(func_type == "other" | is.na(func_type),
#            !(taxa %in% c("copepods", "detritus", "zooplankton", "foraminifera_unidentified",
#                           "globigerinidae", "nauplii", "choanoflagellate",
#                          "strombidium_like", "vorticella_sp", "vorticella_spp"
#                           ))) %>%
#     distinct(taxa))
# 
# View(
#     micro_longer %>% 
#         filter(
#             !taxa %in% vague,
#             func_type == "other",
#             count > 0
#         )
# )
# micro_longer %>% 
#         filter(
#             !taxa %in% vague,
#             func_type == "other",
#             !taxa %in% c("pseudonitzschia_spp", "pseudonitzschia_sp"),
#             count > 0
#         ) %>% 
#     group_by(indx) %>% 
#     summarise(count = n())
```

```{r cmtx-vs-micro-plots, fig.height=9.7, fig.width=19}
plot_micro_cmtx <- function(.data, .group, pig_val, mic_val, ...) {
    
    group <- unique(.data[[.group]])
    for (i in seq(group)) {
        (.data %>%
             filter(func_type == group[i]) %>%
             ggplot(aes(x = !!sym(pig_val),
                        y = !!sym(mic_val),)) +
             
             geom_point(aes(!!!ensyms(...)), show.legend = FALSE) +
             geom_smooth(formula = y ~ x,
                         method  = "lm",
                         se      = FALSE) +
             geom_abline(slope = 1, intercept = 0) +
             labs(title = group[i])
        ) %T>% 
        print()
    }
}

plot_micro_cmtx(
    .data   = cmtx_micro,
    .group  = "func_type",
    pig_val = "conc",
    mic_val = "micro_conc",
    color   = "indx"
)
plot_micro_cmtx(
    .data   = cmtx_micro,
    .group  = "func_type",
    pig_val = "log_conc",
    mic_val = "log_micro_conc",
    color   = "indx"
)
```
```{r bland-altman}
nams <- c("Chlorophytes", "Cryptophytes", "Cyanobacteria", "Diatoms", 
          "Dinoflagellates", "Haptophytes", "Prasinophytes"
          )

pft_bland <- 
    cmtx_micro %>%
    group_by(func_type) %>%
    nest() %>% 
    ungroup() %>%
    bind_cols(nam = nams) %>%
    mutate(
        plt = map2(.x = data, 
                   .y = nams,
                   ~ blandr.draw(.x$conc, .x$micro_conc, plotTitle = .y)),
        info = map(.x = data, 
                   ~ blandr.statistics(.x$conc, .x$micro_conc)),
        shapiro = map(.x = info, 
                      ~ .x  %>%
                         as_tibble()  %>%
                         rstatix::shapiro_test(differences))
    ) %>%
    unnest(shapiro) 

pft_bland$plt
```

```{r save-alt-blan}
if (FALSE) {
    for (i in seq(pft_bland$plt)) {
        ggsave(filename = here("data", "processed", "altman-bland", Sys.Date(),
                               glue("{pft_bland$func_type[i]}",
                                    "{format(Sys.time(), '_%Y%m%d_%H%M%S')}",
                                    ".jpeg")), 
               height   = 7, 
               width    = 14
               )
      Sys.sleep(0.05)
        
        }
}
```

