---
title: "Plotting Data"
author: "Anna Finch"
date: "6/16/2022"
output: html_document
fig_width: 19 
fig_height: 9.7 
---
# ---- Load Libraries ----
```{r setup, include=FALSE}
librarian::shelf(
    librarian, ggplot2, tibble, tidyr, readr, purrr, dplyr, stringr,
    forcats, lubridate, glue, fs, magrittr, here,
    # broom # optional
    
    # additional
    scales, ggthemes, ggtext, huxtable, gt, cowplot, ggthemes, vegan, rstatix
)

library("conflicted")

conflict_prefer("filter", "dplyr")
conflict_prefer("select", "dplyr")

# set season names and order
szn_lab <- c("Winter", "Spring", "Summer", "Autumn")

# load data
pig_dat <-
    here("data", "processed", "combined_pig_dat.csv") %>%
    read_csv(show_col_types = FALSE) %>%
    mutate(
        season = fct_relevel(season, ~ c("W", "Sp", "Su", "F")),
        season = fct_relabel(season, ~ szn_lab),
        name_of_water_body = if_else(
            str_detect(station, "WS") 
            & str_detect(name_of_water_body, "Florida Bay"), 
            "Florida Keys",
            name_of_water_body
            )
        ) 

pig_dat

# set size options of figures
knitr::opts_chunk$set(fig.width = 19, fig.height = 9.7)
```

```{r concentration-vs-time, fig.height=15, fig.width=30}
ggplot(pig_dat, 
       aes(x = date_time_utc, 
           y = allo,
           color = season,
           shape = name_of_water_body)) +
    geom_point(size = 2) +
    labs(
        x = "Year",
        y = "Concentration (mg m<sup>-3</sup>)",
        color = "Season",
        shape = "Region"
    ) +
    scale_y_continuous(expand = c(0,0)) +
    scale_x_datetime(date_breaks = "3 month",
                     date_labels = "%B\n%Y") +
    facet_wrap(~name_of_water_body, nrow = 3,
               scales = "free_y") +
    ggthemes::theme_calc() +
    # theme_classic() +
    theme(
        text = element_text(family = "times"),
        axis.title.y = element_markdown(margin = margin(r = 30, 
                                                        l = 15))
        )
```

```{r scatter-plot}
ggplot(pig_dat, 
       aes(x = tot_chl_a, 
           y = fuco,
           fill = name_of_water_body,
           shape = name_of_water_body)) +
    geom_abline(slope = 1) +
    geom_point(alpha = 0.50, 
               na.rm = T) +
    labs(
        x = "Total Chlorophyll-a",
        y = "Fucoxanthin",
        fill = "Region",
        shape = "Region"
    ) +
    scale_y_continuous(expand = c(0, 0)) +
    scale_shape_manual(values = c(21, 22, 24)) +
    coord_cartesian(ylim = c(0, NA)) +
    facet_wrap(~ season) +
    theme_classic()
```

# ---- Plot Histogram and Violin Plot ----
Plot all pigments for each season
```{r hist-viol, fig.height=9.7, fig.width=19}
pig_long <-
    pig_dat %>%
    pivot_longer(
        cols      = tot_chl_a:tchl_a_tpg, 
        names_to  = "pigment",
        values_to = "conc") %>%
    select(season, pigment, conc, name_of_water_body) %>%
    nest(.by = pigment) %>%
    mutate(
        hist = map2(
            .x = data, 
            .y = pigment,
            ~ .x  %>%
                ggplot(aes(conc, fill = season)) +
                geom_histogram(position = "stack", 
                               bins     = 40,
                               na.rm    = TRUE) +
                labs(
                    title = .y,
                    x     = "Log<sub>\u0065</sub>([Pigment] + 1)",
                    y     = "Frequency",
                    fill  = "Season") +
                scale_x_continuous(trans = log1p_trans()) +
                facet_wrap(facet = ~ name_of_water_body) +
                theme_tufte(base_family = "serif") +
                theme(
                     axis.title.x = element_markdown(margin = margin(t = 20, 
                                                                      b = 5))
                )
            ),
        viol = map2(
            .x = data, 
            .y = pigment,
            ~ .x %>%
                ggplot(aes(x = season, y = conc, color = season)) +
                geom_violin(trim  = TRUE, 
                            na.rm = TRUE) +
                geom_jitter(width = 0.1,
                            size  = 0.5,
                            alpha = 0.5,
                            color = "gray",
                            na.rm = TRUE) +
                labs(
                     title = .y,
                     y     = "Concentration",
                     x     = "Season") +
            
                theme_tufte(base_family = "serif") + 
                scale_y_continuous(expand = c(0, 0)) +
                facet_wrap(facet = ~ name_of_water_body) +
                theme(legend.position = "none")
            )
    )

# show subset of plots
pig_long %>%
    slice_sample(n = 5) %T>%
    walk(.x = .$hist,
         .f = ~ print(.x))  %>% 
    walk(.x = .$viol,
         .f = ~ print(.x)) 
```

```{r chla-boxplot}
chl_a_box <-
    pig_dat %>%
    group_by(name_of_water_body) %>%
    nest() %>%
    mutate(
        plt = map2(
            .x = data,
            .y = name_of_water_body,
            function(.x, .y) {
                ylims <-  c(0, quantile(.x[["tot_chl_a"]], 0.99, na.rm = TRUE))
                
                .x %>%
                ggplot(aes(x = season, 
                           y = tot_chl_a)) +
                geom_boxplot(outlier.shape = NA, na.rm = TRUE) +
                
                stat_summary(
                    fun   = mean,
                    geom  = "point",
                    shape = 20,
                    size  = 8,
                    na.rm = TRUE
                ) +
                
                geom_jitter(width = 0.1, size = 0.5, alpha = 0.5, na.rm = TRUE) +
                
                labs(
                    title = glue("{.y}: [Chlorophyll-a]"), 
                    x     = "Season",
                    y     = "Concentration (mg m<sup>-3</sup>)") +
                
                scale_y_continuous(expand = c(0, 0)) +
                coord_cartesian(y = ylims) +
                
                # theme
                ggthemes::theme_tufte() +
                theme(text = element_text(size = 24, family = "serif"),
                      axis.title.y = element_markdown(margin = margin(r = 30, 
                                                                      l = 15)),
                      axis.title.x = element_markdown(margin = margin(t = 20, 
                                                                      b = 5)),
                      axis.text.x  = element_text(color = "black"),
                      axis.text.y  = element_text(color = "black"),
                      axis.ticks.x = element_blank()) 
                
                }
        )
    )

chl_a_box$plt

if (FALSE) {
  chl_a_box %>%
    ungroup() %>%
    walk2(
      .x = .$name_of_water_body,
      .y = .$plt,
      .f = (\(.x)
      .x %>%
        str_to_lower() %>%
        str_replace_all("\\s", "_") %>%
        glue(., "_chla{format(Sys.time(), '_%Y%m%d_%H%M%S')}.jpeg") %>%
        save_plot(
          filename    = .,
          path        = here("data", "plots", Sys.Date()),
          plot        = .y,
          base_height = 9.7,
          base_width  = 19,
          dpi         = 600,
          units       = "in",
          device      = "png",
          bg          = "white"
        ))
    )
}
```


```{r size-fractionation-boxplots, fig.height=10, fig.width=20}
size_frac_plt <-
    pig_dat %>%
    pivot_longer(
        cols      = f_micro:pico,
        names_to  = "size_frac",
        values_to = "conc"
    ) %>%
    select(name_of_water_body, season, size_frac, conc) %>%
    nest(.by = size_frac) %>%
    mutate(
        labels = case_when(
            str_detect(size_frac, "micro") ~ "Microplankton (>20 &mu;m)",
            str_detect(size_frac, "pico")  ~ "Picoplankton (<2 &mu;m)",
            str_detect(size_frac, "nano")  ~ "Nanoplankton (2 - 20 &mu;m)"
        ),
        labels = if_else(str_detect(size_frac, "f_"), 
                         str_c("Fraction of ", labels), 
                         labels),
        plt = map2(
            .x = data,
            .y = labels,
            function(.x, .y) {
                
                if (str_detect(.y, "Frac")) {
                     y_name <- "Percent (%)"
                     y_lim  <- c(0, 1)
                } else {
                    y_name  <- "Concentration (mg m<sup>-3</sup>)"
                    y_lim   <- c(0, quantile(.x[["conc"]], 0.99, na.rm = TRUE))
                }

                .x %>%
                ggplot(
                       aes(
                           x     = season,
                           y     = conc,
                           fill = name_of_water_body
                       )) +
                geom_boxplot(na.rm = TRUE, linewidth = 0.2) +
                    {if (str_detect(y_name, "Frac")) {
                        scale_y_continuous(labels = label_percent())
                    }} +
                    
                labs(
                    title = .y,
                    x     = "Season",
                    y     = y_name,
                    fill = "Location"
                ) +
                scale_fill_brewer(palette = "Dark2") +
                coord_cartesian(ylim = y_lim) +
                theme_tufte() +
                theme(
                    text = element_text(size = 24, family = "serif"),
                    plot.title = element_markdown(),
                    axis.text.x  = element_text(color = "black"),
                    axis.text.y  = element_text(color = "black"),
                    axis.title.y = element_markdown(size = 24,
                                                    margin = margin(r = 30, 
                                                                    l = 15)),
                    axis.title.x = element_markdown(margin = margin(t = 20, 
                                                                    b = 5))
                    

                )
                
            }
    ))
size_frac_plt$plt
```

```{r size-frac-stack-bar, fig.height=11, fig.width=30}
plt_stack <-
    pig_dat %>%
    pivot_longer(
        cols      = f_micro:f_pico,
        names_to  = "size_frac",
        values_to = "frac") %>%
    # mutate(station = fct_reorder(station, lon)) %$% 
    # levels(station)
    nest(.by = name_of_water_body) %>%
    mutate(plt = map2(
        .x = data,
        .y = name_of_water_body,
        function(.x, .y) {
            .x %>%
                mutate(
                    station = fct_reorder(station, lon)
                ) %>%
                
                ggplot(aes( 
                    x    = station, 
                    y    = frac,
                    fill = size_frac)) +
                
                geom_bar(
                    position = "fill", 
                    stat     = "identity",
                    na.rm    = TRUE,
                    # position = position_dodge(width = 0.9)
                    ) +
                
                # labels
                labs(
                    title = .y,
                    x     = "Station", 
                    y     = "Percent (%)", 
                    fill  = "Phytoplankton Size Class") +
                
                 scale_fill_brewer(
                    palette = "Dark2",
                    labels  = c("*f*<sub>micro</sub> (>20 &mu;m)",
                                "*f*<sub>nano</sub> (2 - 20 &mu;m)",
                                "*f*<sub>pico</sub> (<2 &mu;m)")
                    ) +
                scale_y_continuous(labels = label_percent()) +
                scale_x_discrete(guide = guide_axis(n.dodge = 1, angle = 90)) +
                facet_wrap( ~ season) +
                ggthemes::theme_tufte() +
                theme(
                    legend.text = element_markdown(),
                    plot.title = element_text(size = 30),
                    strip.text.x = element_text(size = 20),
                    axis.text.x = element_text(size = 15),
                    panel.spacing.x = unit(25,"pt"),
                    panel.border = element_rect(fill = NA)
                      )
        }
    )) 

plt_stack$plt

# save plots
if (FALSE) {
plt_stack %>%
    ungroup() %>%
    walk2(
        .x = .$name_of_water_body,
        .y = .$plt,
        .f = ~ .x %>%
            str_to_lower() %>%
            str_replace_all(" ", "_") %>%
            glue(., "_frac_bar{format(Sys.time(), '_%Y%m%d_%H%M%S')}.jpeg") %>% 
            save_plot(
                filename    = .,
                path        = here("data", "plots", Sys.Date()),
                plot        = .y,
                base_height = 9.7,
                base_width  = 19,
                dpi         = 600,
                units       = "in",
                device      = "png",
                bg          = "white")
        )
}

```

```{r size-frac-table}
frac_gt <-
    pig_dat %>%
    pivot_longer(
        cols      = f_micro:f_pico,
        names_to  = "size_frac",
        values_to = "frac") %>%
    summarise(across(.cols = frac, 
                     .fns  = list(avg = mean, sd = sd), 
                     ),
              .by = c(season, size_frac)
              ) %>% 
    dplyr::mutate(
        .keep = "none",
        season,
        size_frac,
        f = glue::glue("{round(frac_avg, 2)}\u00B1{round(frac_sd, 2)}"),
    ) %>% 
    pivot_wider(names_from = "size_frac", values_from = "f") %>% 
    gt(
        rowname_col   = "season",
        groupname_col = NULL
    ) %>% 
    cols_label(
        f_micro = md("***f*<sub>micro</sub>** (>20 &mu;m)"),
        f_nano = md("***f*<sub>nano</sub>** (2 - 20 &mu;m)"),
        f_pico = md("***f*<sub>pico</sub>** (<2 &mu;m)")) %>%
    tab_options(
        table_body.hlines.width = 0,
        table_body.vlines.width = 0,
        stub.border.width = 0
    ) %>%
    opt_table_font("serif") 

frac_gt

if (FALSE) {
    frac_gt %>%
    gtsave(
        filename = here("data", "plots", Sys.Date(),
                        glue("fract_table", 
                             "{format(Sys.time(), '_%Y%m%d_%H%M%S')}.html")
                        )
        )
}
```

```{r plotting-chemtax-data}
#season_year order vector
# seasonyr_order <- c("Spring 2016", "Summer 2016 (No Data)", "Autumn 2016", "Winter 2016-2017 (No Data)", "Spring 2017", 
#                     "Summer 2017", "Autumn 2017", "Winter 2017-2018", "Spring 2018",
#                     "Summer 2018", "Autumn 2018", "Winter 2018-2019", "Spring 2019", 
#                     "Summer 2019", "Autumn 2019", "Winter 2019-2020", "Spring 2020 (No Data)",
#                     "Summer 2020", "Autumn 2020", "Winter 2020-2021", "Spring 2021")

cmtx_avgs <-
    here("data", "processed", "chemtax_w_meta_rm_dup.csv") %>%
    read_csv(show_col_types = FALSE) %>%
    mutate(
        season = fct_relevel(season, ~ c("Winter","Spring", 
                                         "Summer", "Autumn")),
        season = fct_relevel(season, ~ szn_lab),
        ) %>%
    select(-c(hplc_gsfc_id, pi, cruise:bottle, filter_type:comments,
              cluster_code)) %>%
    
    # add PFT concentrations to get total chlorophyll-a
    rowwise() %>%
    mutate(total_chl_a = sum(c_across(chloro:pras)), 
           .before     = chloro) %>%
    ungroup()
```


```{r plotting-chemtax-data}
cmtx_long <-
    cmtx_avgs  %>%
    pivot_longer(
        cols      = chloro:last_col(),
        names_to  = "func_type",
        values_to = "conc") %>%
    group_by(func_type) %>%
    nest() %>%
    ungroup() %>%
    mutate(
        hist = map2(
            .x = data, 
            .y = func_type,
            ~ .x  %>%
                ggplot(aes(conc, fill = season)) +
                geom_histogram(position = "stack", 
                               bins     = 40,
                               na.rm    = TRUE) +
                labs(
                    title = .y,
                    x     = "Log<sub>\u0065</sub>([PFT] + 1)",
                    y     = "Frequency",
                    fill  = "Season") +
                scale_x_continuous(trans =log1p_trans()) +
                facet_wrap(facet = ~ name_of_water_body) +
                theme_tufte(base_family = "serif") +
                theme(
                     axis.title.x = element_markdown(margin = margin(t = 20, 
                                                                      b = 5)),
                     plot.title = element_text(size = 40),
                     strip.text = element_text(size = 30)
                )
         )
    )
cmtx_long$hist
```


```{r plotting-chemtax-data}
cmtx_long <- 
    cmtx_long %>%
    select(-last_col()) %>%
    unnest(data) %>%
    filter(station != 60) %>% 
    mutate(
        season_year = case_when(
            str_detect(season, "Aut|Spr|Sum") ~ glue("{season} {year}"),
            str_detect(month, "Jan|Feb") ~ glue("{season} {year-1}-{year}"),
            str_detect(month, "Dec") ~ glue("{season} {year}-{year+1}"),
        ),
        season_year = fct_inorder(season_year),
        season_year = fct_expand(
            season_year, "Summer 2016 (No Data)", 
                "Winter 2016-2017 (No Data)", "Spring 2020 (No Data)"
            ),
        season_year = fct_relevel(season_year, 
                                  "Summer 2016 (No Data)", 
                                  after = 1),
        season_year = fct_relevel(season_year, 
                                  "Winter 2016-2017 (No Data)", 
                                  after = 3),
        season_year = fct_relevel(season_year, 
                                  "Spring 2020 (No Data)", 
                                  after = 16),
        .after = season
        )  %>%
    
    # added rows with the missing seasons so that the facet grid will have 
    # seasons by column
    complete(season_year, season) %>%
    mutate(
        station = if_else(is.na(station), "3", station)
    )  
```



```{r, fig.width=30, fig.height=15}
# CHEMTAX stacked bar graph
cmtx_long  %>% 
    ggplot(
       aes(
           x     = station,
           y     = conc,
           fill  = func_type,
           color = func_type
       )) +
    
    geom_bar(position = "fill", 
             stat     = "identity",
             na.rm    = TRUE) +
    
    labs(x     = "Station", 
         y     = "Percent (%)", 
         fill  = "Phytoplankton Functional Type",
         color = "Phytoplankton Functional Type") +
    scale_y_continuous(labels = scales::label_percent()) +
    
    facet_wrap(~ season) +
    
    theme_tufte()
```
```{r, fig.width=30, fig.height=15}
tol_muted <- c('#88CCEE', '#44AA99', '#117733', '#332288', '#DDCC77', '#999933',
               '#CC6677', '#882255', '#AA4499', '#BBBBBB', '#FFAABB')


# CHEMTAX stacked bar graph with ratio to chlor-a, organized by station
cmtx_long %>% 
    mutate(station = fct_reorder(station, lon, .na_rm = FALSE)) %>% 
    # filter(!is.na(station)) 
    ggplot(aes(
        fill  = func_type,
        color = func_type,
        y     = conc,
        x     = station,
    )) +
    geom_bar(position = "fill", 
             stat     = "identity",
             na.rm    = TRUE) +
    
    labs(x     = "Station",
         y     = "Relative Ratio",
         fill  = "Phytoplankton Functional Type",
         color = "Phytoplankton Functional Type") +
    
    scale_fill_manual(values  = tol_muted) +
    scale_color_manual(values = tol_muted) +
    scale_y_continuous(labels = label_percent()) +
    
    facet_wrap( ~ season_year, ncol = 4) +
    
    # theme
    theme_classic() +
    theme(
        text             = element_text(family = "serif", size = 16),
        axis.title       = element_text(size = 18),
        legend.position  = c(0.6, 0.05),
        legend.direction = "horizontal"
    ) 

if (FALSE) {
    save_plot(
        filename    = here("data", "plots", Sys.Date(),
                           glue("phyto_func_type_bar_ratio", 
                             "{format(Sys.time(), '_%Y%m%d_%H%M%S')}.jpeg")
                           ),
        plot        = last_plot(),
        base_height = 9.7,
        base_width  = 19,
        dpi         = 600,
        units       = "in",
        device      = 'png')
    }
```
```{r, fig.width=30, fig.height=15}
# chemtax stacked bar graph (not ratio), organized by station
cmtx_long %>% 
    mutate(station = fct_reorder(station, lon, .na_rm = FALSE)) %>%
    summarize(conc = mean(conc, na.rm = TRUE),
              .by  = c(season_year, station, func_type)) %>% 
    ggplot(aes(
        fill  = func_type,
        color = func_type,
        y     = conc,
        x     = station
    )) +
    geom_bar(stat = "identity") +
    labs(
        x     = "Station",
        y     = "Concentration of Chlorophyll-a (mg m<sup>-3</sup>)",
        fill  = "Phytoplankton Functional Type",
        color = "Phytoplankton Functional Type"
    ) +
    
    scale_fill_manual(values  = tol_muted) +
    scale_color_manual(values = tol_muted) +
    
    facet_wrap( ~ season_year, ncol = 4) +
    
    # theme
    theme_classic() +
    theme(text = element_text(family = "serif", size = 12),
          axis.title.y     = element_markdown(size = 10),
          legend.position  = c(0.6, 0.05),
          legend.direction = "horizontal"
          )

if (FALSE) {
    save_plot(
        filename    = here("data", "plots", Sys.Date(),
                            glue("phyto_func_type_bar", 
                             "{format(Sys.time(), '_%Y%m%d_%H%M%S')}.jpeg")
                           ),
        base_height = 9.7,
        base_width  = 19,
        dpi         = 600,
        units       = "in",
        device      = 'png')
    }
```
# Timeseries Plots
## Timesseries PFT with LOESS Smoother
 
```{r pft-ts-loess, fig.width=30, fig.height=15}
# point plot with smoothing line for 1 functional group, colored by season
cmtx_avgs %>%
    pivot_longer(
        cols      = chloro:pras,
        names_to  = "func_type",
        values_to = "conc"
    ) %>%
    mutate(
        conc_ratio = conc / total_chl_a
    ) %>%
    select(func_type, date_time_utc, season, conc_ratio) %>%

    ggplot(aes(x = date_time_utc, y = conc_ratio, color = season)) +
    geom_point() +
    geom_smooth(
        formula = y ~ s(x),
        method = "gam",
        # span = 1,
        se = FALSE) +
    labs(
        x = NULL,
        y = "Pigment:Chlorophyll-a",
        color = NULL
    ) +
    scale_x_datetime(breaks = "1 year",
                     labels = label_date("%Y")) +
    scale_color_brewer(palette = "Dark2") +
    facet_wrap(~ func_type) +
    theme_tufte()

```
## Timeseries with Diatoms
```{r diat-ts}
# time series for diatom at specific stations
cmtx_longer3 <-
    cmtx_avgs %>%
    filter(str_detect(station, "10|WS|16")) %>%
    mutate(diat  = diat1  + diat2,
           cyano = cyano2 + cyano4,
           hapt  = hapt6  + hapt8) %>%
    
    # remove columns
    select(-c(diat1, diat2, cyano2, cyano4, hapt6, hapt8)) %>%
    
    pivot_longer(
        cols      = chloro:hapt,
        names_to  = "func_type",
        values_to = "conc") %>%
    # group_by(station, func_type, date_time_utc) %>%
    # summarise(
    reframe(    
        pick(season),
        avg_conc = mean(conc),
        .by      = c(station, func_type, date_time_utc)
              ) %>%
    distinct()
```


```{r diat-ts, fig.width=30, fig.height=15}
# station 16
cmtx_longer3 %>% 
    filter(str_detect(func_type, "diat|cyano") & station == "16") %>% 
    ggplot(aes(x     = date_time_utc, 
               y     = avg_conc, 
               color = func_type, 
               fill  = func_type)
           ) +
    geom_point() +
    geom_line() +
    facet_wrap(facets = ~ "station") +
    
    ggthemes::theme_clean()
    
# point plot with smoothing line for all functional groups
cmtx_long %>%
    filter(year < 2019) %>%
    mutate(ratio = conc / total_chl_a) %>%
    ggplot(
        aes(
        x     = date_time_utc,
        y     = ratio,
        color = func_type
    )) +
    geom_smooth(se = FALSE, method = "gam", formula = y ~ s(x)) +
    geom_point() +
    labs(
        x = "Year",
        y = "Pigment:Total Chlorophyll-a"
    ) +
    facet_wrap(~ func_type) +
    
    ggthemes::theme_clean()
```


```{r diat-ts1}
# was commented out
aov(dino ~ season * as.factor(year),# + season:as.factor(year), 
    data = cmtx_avgs) %>%
    summary()


lm(scale(crypto) ~ season + year, 
   data = cmtx_avgs) %>%
    summary() 

# this doesnt exists here `cmtx_longer`
# cmtx_kruskal2 <- 
    cmtx_long %>%
    filter(!is.na(func_type)) %>%
    group_by(func_type) %>%
    kruskal_test(conc ~ season_year)
```


```{r manova}
# cmtx_dunn2 <- 
    cmtx_long %>%
    group_by(func_type) %>%
    dunn_test(
        conc ~ season_year, 
        p.adjust.method = "bonferroni",
        detailed = TRUE
        ) %>%
    mutate(
        p = num(p, digits = 3),
        p.adj = num(p.adj, digits = 3),
    ) %>%
    nest(.by = func_type) %$%
    walk2(
        .x = func_type,
        .y = data,
        (\(x, y) mutate(y, func_type = x,
                        .before = 1) %>%
             filter(p < 0.1) %>%
             # arrange(p) %>%
           print())
    )


# MANOVA test
cmtx_man <- cmtx_avgs %>%
    select(chloro:last_col()) %>%
    as.matrix() 

manova(cmtx_man ~ season, data = cmtx_avgs) %>%
    summary()
```
# Photoprotective Index
```{r photoprotective-index}
pigm_pi <- mutate(pig_dat, pi = ppc/tot_chl_a)

ggplot(pigm_pi, 
       aes(x = date_time_utc, 
           y = pi, 
           color = season)) +
    geom_point()

# with SeaBass calculation for PPC
ggplot(pigm_pi, 
       aes(
           x = season, 
           y = pi,
           fill = season)) +
    
    geom_boxplot() +
    labs(
        x = "Season",
        y = "Photoprotection Index (PI)") +
    
    theme_classic() +
    theme(legend.position = "none", 
          text = element_text(family = "serif", size = 12)
          )

if (FALSE) {
    save_plot(
        filename    = here("data", "plots",
                           glue("pi_bar", 
                                 "{format(Sys.time(), '_%Y%m%d_%H%M%S')}.jpeg")
                           ),
        plot        = last_plot(),
        base_height = 6,
        base_width  = 10,
        dpi         = 600,
        units       = "in",
        device      = 'png'
    )
    }
```


```{r photoprotective-index, fig.height=15, fig.width=30}
ggplot(pigm_pi, 
       aes(
           x = psc,
           y = ppc,
           shape = season,
           color = season
           )) +
    geom_point(size = 4, alpha = 0.8) +
    geom_abline(slope = 1, intercept = 0) +
    theme_classic() +
    labs(
        y = "PPCs",
        x = "PSCs",
        color = "Season",
        shape = "Season"
    ) +
    theme(text = element_text(family = "serif", size = 20),
          legend.position = c(0.8, 0.8)) +
    scale_y_continuous(expand = c(0, 0)) +
    scale_x_continuous(expand = c(0, 0)) + 
    facet_wrap(~season, nrow = 2)

if (FALSE) {
    save_plot(
        filename    = here("data", "plots",
                           glue("psc_vs_ppc", 
                                 "{format(Sys.time(), '_%Y%m%d_%H%M%S')}.jpeg")
                           ),
        plot        = last_plot(),
        base_height = 6,
        base_width  = 10,
        dpi         = 600,
        units       = "in",
        device      = 'png'
    )
}
```
```{r kruskal-dunn-pi}
# pi_kruskal <- 
    pigm_pi %>% 
    # kruskal_test(pi ~ season + year)
    kruskal_test(pi ~ season)

# pi_dunn <- 
    pigm_pi %>%
    dunn_test(pi ~ season, 
              p.adjust.method = "bonferroni")

```

```{r station-seasonally-yearly-avgs}
cmtx_avgs_new <- cmtx_avgs %>% 
    mutate(
        diat  = diat1  + diat2,
        cyano = cyano2 + cyano4,
        hapt  = hapt6  + hapt8,
        total = chloro + crypto + diat + dino + hapt + pras + cyano
           )

cmtx_stat <-  cmtx_avgs_new %>% 
    summarise(across(chloro:hapt,
                 list(
                     avg = (\(x) mean(x, na.rm = TRUE)), 
                     sd  = (\(x) sd(x, na.rm = TRUE)), 
                     var = (\(x) var(x, na.rm = TRUE)))),
              .by = c(year, season, station))

cmtx_fract <-
    cmtx_avgs_new %>% 
    mutate(
        season,
        station,
        across(chloro:hapt, ~ .x / total, .names = "frac_{.col}")
        ) %>% 
    select(date_time_utc:season, frac_chloro:frac_pras) %>% 
    pivot_longer(
        frac_chloro:frac_pras,
        names_to     = "func_type",
        values_to    = "frac",
        names_prefix = "frac_"
    )

max_fract <- 
    cmtx_fract %>%
    summarise(max_frac = max(frac),
              .by = sample) %>% 
    left_join(cmtx_fract, 
              by = c("max_frac" = "frac"))
```

```{r lat-lon-table}
lat_lon_dat <- pig_dat %>%
    filter(name_of_water_body == "Florida Keys", station != "60") %>%
    dplyr::select(station, lat, lon) %>% 
    distinct(station, lat, lon)

lat_lon_tbl <- lat_lon_dat %>% 
    gt(
        rowname_col   = "station",
        groupname_col = NULL
    ) %>%
    
    cols_label(
        lat = md("Latitude (&deg;)"),
        lon = md("Longitude (&deg;)")) %>% 
    
    tab_options(
        table_body.hlines.width = 0,
        table_body.vlines.width = 0,
        stub.border.width       = 0
    ) %>%
    
    opt_table_font("serif")

lat_lon_tbl 

if (FALSE) {
    gtsave(
        lat_lon_tbl,
        filename = here("data", "plots", 
                        glue("lat_lon_table", 
                             "{format(Sys.time(), '_%Y%m%d_%H%M%S')}.html")
                        )
        )
    }
```