---
title: "Seascapes"
author: "Anna Finch"
date: "8/15/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("ggplot2")
library("tibble")
library("tidyr")
library("readr")
library("purrr")
library("stringr")
library("forcats")
library("lubridate")
library("glue")
library("fs")
library("magrittr")
# library("broom") # optional
library("raster")
library("sp")
library("rgdal")
library("maptools")
library("rgeos")
library("vegan")
library("ggord")
library("dplyr")


# ---- set path variables ----
root       <- rprojroot::find_rstudio_root_file()
seasc.path <- paste0(root, "/data/raw/seascapes/")
path_out   <- paste0(root, "/data/processed/")

# ---- source extract function ----
source(paste0(root, "/scripts/seascapes_extract.R"))


dirsea <- "/data/raw/seascapes/"
seasc.path = paste0(root, dirsea)
dir2 <- "//data//processed//"
dir3 <- "//data//raw//"

# ---- unzip seascapes file ----
# get "fknms_global_monthly.zip" from https://shiny.marinebon.app/seascapes/. 
# select "Florida Keys" in the region pull-down tab and click "all grids (.zip)"
# to download Sanctuary files. 
unzip(paste0(seasc.path, "fknms_global_monthly.zip"), exdir = seasc.path)

<<<<<<< HEAD
# to download timeseries, select "timeseries.csv"
seasc_tmser <- read.csv(paste0(root, dir3, "fknms_global_monthly_CLASS.csv")) %>% 
    filter(date > '2016-01-01',
           date < '2021-12-31') %>% 
    mutate(date = as.Date(date))

=======
# ---- load chemtax data ----
dir2 <- "//data//processed//"
>>>>>>> cd19a0c9cfa6b9b57b3439c1f83f1cae43963356
path_out <-  paste0(root,dir2)
# cmtx_avgs <- read.csv(paste0(path_out, "chemtax_with_metadata.csv"))
env_cmtx <- read.csv(paste0(path_out, "cmtx_env_data.csv")) %>% 
    mutate(season= forcats::fct_relevel(season, "Winter", "Spring", "Summer", "Autumn"))

```

```{r}
# making new column in df with year and month in format "YYYY.MM" to match how
# the seascapes .tif files are named

# cmtx_sea <- env_cmtx %>% 
#    mutate(yr_mth = substring(env_cmtx$date_time_utc, 1, 7),
#           yr_mth = gsub(pattern = "-", replacement = ".", x = yr_mth))
# mth_yr_df <- base::as.data.frame(unique(cmtx_sea$yr_mth)) %>% 
#   rename("yr_mth" = "unique(cmtx_sea$yr_mth)")

cmtx_sea <-
    cmtx_avgs %>%
    mutate(yr_mth = as_date(date_time_utc) %>% format("%Y.%m"))
           
# ---- extract year month col ----
mth_yr_df <- cmtx_sea %>%
    select(yr_mth) %>%
    distinct()



# making df. one column is the file names and the other column is the year and
# month for the file in format "YYYY.MM" to match with the other list
file.seascapes <-
  fs::dir_ls(path = seasc.path,
             # included ^[^~]* to not match ~, means that a file is opened
             regexp = "^[^~]*\\.tif$") %>% 
    as.data.frame() %>%
    # as_tibble() %>% 
    mutate(yr_mth = gsub(pattern = paste0(seasc.path, "grd_CLASS_"), replacement = "", x = .),
           yr_mth = gsub(pattern = ".15.tif", replacement = "", x = yr_mth))

# selecting the file names that correspond to the year and month combos that the 
# cruises had
seascapes_match <- left_join(mth_yr_df,
                             file.seascapes,
                             by = c("yr_mth")) %>%
    na.omit()
file.sea <- seascapes_match$. %>% 
    str_sort()

```

```{r }
# making empty data frame to be filled with seascapes values
seascapes_df <-
    as_tibble(matrix(ncol = 4, nrow = 1),
              .name_repair = ~ c('lon', 'lat', 'seascape', "yr_mth"))


# going through each seascapes file and extracting seascapes for each station
# and adding them to a dataframe
# for (i in 1:length(file.sea)) {
for (i in seq(file.sea)) {
    filename <- file.sea[i]
    
    #extract month and year in format "YYYY.MM"
    yr_mth <- gsub(pattern = paste0(seasc.path, "grd_CLASS_"), replacement = "", x = filename) %>% 
        gsub(pattern = ".15.tif", replacement = "")
    
    #make temporary dataframe with seascapes, coordinates, and year+month for cruise
    seascapes_temp <- extract_seascapes(filename, cmtx_sea) %>% 
        mutate(yr_mth = yr_mth)
    
    #combine the dataframes with seascapes for each cruise
    seascapes_df <- rbind(seascapes_df, seascapes_temp)
}

# join the chemtax and seascapes data
cmtx_sea2 <- cmtx_sea %>% 
    left_join(seascapes_df) %>% 
    drop_na(seascape)


```

```{r}
#CAP with Bray-Curtis

seascspec <- cmtx_sea2 %>% 
    dplyr::select(chloro:pras)

seasc.cap <- capscale(seascspec ~ seascape, cmtx_sea2, dist = "bray")

plot(seasc.cap)
```


```{r seascapes cca}
sea_matrix <- cmtx_sea2 %>% 
    dplyr::select(chloro:pras)

sea_cca <- cca(sea_matrix ~ temp +sal + par + seascape, data = cmtx_sea2, na.action = na.omit)
new.lab <- list(temp = "Temp", sal = "Sal", par = "PAR", seascape ="Seascape")

ggord(sea_cca, size = 4, grp_in = cmtx_sea2 %>% drop_na(temp,par:sal) %$% as.character(seascape),
      ellipse = F, ptslab = T, addsize = 6, ylim = c(-6.25, 6.25), xlim = c(-4, 5),
      repel = T, txt = 6, vec_lab = new.lab, grp_title = "Seascape Class"
      ) +
    theme_classic()+
    theme(text=element_text(family="serif", size=20), legend.position = c(0.15, 0.9)) 

cowplot::save_plot(filename = paste0(root,"/data/plots/seascape_cca", 
           format(Sys.time(), '_%Y%m%d_%H%M%S'),
           ".jpg"), 
          plot = last_plot(),
          base_height = 10,
          base_width = 8,
          dpi = 600, units = "in", device='png')

```

```{r seasonal seascapes cca}
seasons <- c("Winter", "Spring", "Summer", "Autumn")

for (i in 1:length(seasons)) {
    temp_sea_df <-  cmtx_sea2 %>% 
        filter(season == seasons[i])
    temp_sea_mat <- temp_sea_df %>% 
        select(chloro:pras)
    
    temp_cca <- cca(temp_sea_mat ~ temp +sal + par, data = temp_sea_df, na.action = na.omit)
    ggord(temp_cca, size = 4, grp_in = temp_sea_df %>% drop_na(temp,par:sal) %$% as.character(seascape),
          ellipse = F, ptslab = T, addsize = 6, ylim = c(-6.25, 6.25), xlim = c(-4, 5),
          repel = T, txt = 6, vec_lab = new.lab, grp_title = "Seascape Class"
          ) +
        theme_classic()+
        theme(text=element_text(family="serif", size=20), legend.position = c(0.15, 0.9))
    
    # cowplot::save_plot(filename = paste0(root,"/data/plots/seascape_cca", seasons[i], 
    #            format(Sys.time(), '_%Y%m%d_%H%M%S'),
    #            ".jpg"), 
    #           plot = last_plot(),
    #           base_height = 10,
    #           base_width = 8,
    #           dpi = 600, units = "in", device='png')
}

```

```{r}
seasc_encoded <- data.frame(matrix(ncol=5, nrow = length(cmtx_sea2$seascape)))
colnames(seasc_encoded) <- c("class_3", "class_13", "class_15",
                             "class_21", "class_27")
seasc_encoded[is.na(seasc_encoded)] = 0

for (i in 1:length(cmtx_sea2$seascape)) {
    if (cmtx_sea2$seascape[i] == 15) {
        seasc_encoded$class_15[i] <- 1
    } else if (cmtx_sea2$seascape[i] == 27) {
        seasc_encoded$class_27[i] <- 1
    } else if (cmtx_sea2$seascape[i] == 21) {
        seasc_encoded$class_21[i] <- 1
    } else if  (cmtx_sea2$seascape[i] == 13) {
        seasc_encoded$class_13[i] <- 1
    } else if (cmtx_sea2$seascape[i] == 3) {
        seasc_encoded$class_3[i] <- 1
    }
}
seasc_encoded <- cbind(seasc_encoded, cmtx_sea2$season)

seasc_encoded <- seasc_encoded %>% 
    dplyr::rename("season" = `cmtx_sea2$season`)
# 
# sea_cca <- cca(sea_matrix ~ class_3 + class_13 + class_15 + class_21 + class_27, data = seasc_encoded, na.action = na.omit)
# new.lab <- list(class_3 = "3", class_13 = "13", class_15 = "15", class_21 = "21",
#                 class_27 = "27")

#ANOVA to see if seascapes varied with seasons
summary(aov(class_21 ~ season, data=seasc_encoded))

#PERMANOVA to see if seascapes varied with seasons
set.seed(340598345)
all_test <- adonis2(seasc_encoded[1:5] ~ season, data = cmtx_sea2, method = "bray")


seasc_pca <- prcomp(seasc_encoded[1:5], scale. = TRUE)
ggplot2::autoplot(seasc_pca, size = 5, data = cmtx_sea2, colour = "season", loadings = T,
                  loadings.colour = 'blue', loadings.label = T, loadings.label.size = 10,
                  loadings.label.colour = "blue", loadings.label.position = (c(0.5, 0.5))) +
    theme_classic() +
    theme(text=element_text(family="serif", size=40),
               legend.position = c(0.8, 0.85),
                    legend.text = element_text(family="serif", size=30)) +
    scale_colour_discrete(name = "Season")

save_plot(filename = paste0(root,"/data/plots/pca", 
           format(Sys.time(), '_%Y%m%d_%H%M%S'),
           ".jpg"), 
          plot = last_plot(),
          base_height = 8,
          base_width = 15,
          dpi = 600, units = "in", device='png')


```


```{r}
#doing some calculations
#information on the seascapes classes: https://shiny.marinebon.app/seascapes/classes.html

#looking at the number of samples that are dominated by each class
seasc_summary <- cmtx_sea2 %>% 
    group_by(seascape) %>% 
    summarize(n())

#looking at the number of samples that are dominated by each class per season
seasc_summary2 <- cmtx_sea2 %>% 
    group_by(seascape, season) %>% 
    summarize(n())

# to look at what seascape dominated samples with high and low chlorophyll-a values
view(cmtx_sea2 %>% 
         mutate(diat = diat1 + diat2,
           cyano = cyano2 + cyano4,
           hapt = hapt6 + hapt8,
           total = chloro + crypto + diat + dino + hapt + pras + cyano))

#look at what PFTs dominate each seascape class
sea_fract <- cmtx_sea2 %>% 
    mutate(diat = diat1 + diat2,
           cyano = cyano2 + cyano4,
           hapt = hapt6 + hapt8,
           total = chloro + crypto + diat + dino + hapt + pras + cyano) %>% 
    mutate(year = year,
              season = season,
              station = station,
              frac_chloro = chloro/total,
           frac_crypto = crypto/total,
           frac_cyano = cyano/total,
           frac_diat = diat/total,
           frac_dino = dino/total,
           frac_hapt = hapt/total,
           frac_pras = pras/total)%>% 
    select(hplc_gsfc_id:season, seascape, frac_chloro:frac_pras)
```

```{r NDMS}
set.seed(1355453)
nmds <- metaMDS(as.matrix(sea_matrix), distance = "bray")

#extract NMDS scores (x and y coordinates) for sites from newer versions of vegan package
data.scores = as.data.frame(scores(nmds)$sites)

#add columns to data frame 
data.scores$sample = cmtx_sea2$sample
data.scores$season = cmtx_sea2$season
data.scores$seascape = cmtx_sea2$seascape
 
head(data.scores)
Tol_muted <- c('#88CCEE', '#44AA99', '#117733', '#332288', '#DDCC77', '#999933','#CC6677', '#882255', '#AA4499', '#BBBBBB', '#FFAABB')

xx = ggplot(data.scores, aes(x = NMDS1, y = NMDS2)) + 
    # geom_point(size = 4, aes(shape = season, color = factor(seascape)))+
    geom_point(size = 4, aes(color = factor(seascape)))+
    theme(text=element_text(family="serif", size=40),
    #     axis.text.y = element_text(colour = "black", size = 12, face = "bold"),
    # axis.text.x = element_text(colour = "black", face = "bold", size = 12),
    # legend.text = element_text(size = 12, face ="bold", colour ="black"),
    legend.position = c(0.84, 0.3), 
    # axis.title.y = element_text(face = "bold", size = 14),
    # axis.title.x = element_text(face = "bold", size = 14, colour = "black"),
    # legend.title = element_text(size = 14, colour = "black", face = "bold"),
    panel.background = element_blank(), panel.border = element_rect(colour = "black", fill = NA, size = 1.2),
    legend.key=element_blank()) +
    labs(x = "NMDS1", color = "Seascape Class", y = "NMDS2", shape = "Season") +
    scale_shape_manual(values = c(0, 1, 2, 5, 3))+
    labs(x = "NMDS1", colour = "Seascape Class", y = "NMDS2") +
    scale_colour_manual(values = Tol_muted) 
 
xx

cowplot::save_plot(filename = paste0(root,"/data/plots/seascape_nmds", 
           format(Sys.time(), '_%Y%m%d_%H%M%S'),
           ".jpg"), 
          plot = last_plot(),
          base_height = 8,
          base_width = 16,
          dpi = 600, units = "in", device='png')


```

```{r ANONISM}
ano1 <- anosim(as.matrix(sea_matrix), factor(cmtx_sea2$seascape), distance = "bray", permutations = 100)
ano1

ano2 <- anosim(as.matrix(sea_matrix), factor(cmtx_sea2$season), distance = "bray", permutations = 100)
ano2

```

```{r}
#which functional types dominated each seascape class?

sea_pft <- cmtx_sea2 %>%
    # group_by(season, seascape) %>%
    # summarize_at(vars(chloro:pras), mean) %>%
    mutate(total = chloro + crypto + diat1 + diat2 + dino + hapt6 + hapt8 +
           pras + cyano2 + cyano4,
       frac_chloro = chloro/total,
       frac_crypto = crypto/total,
       frac_cyano2 = cyano2/total,
       frac_cyano4 = cyano4/total,
       frac_diat1 = diat1/total,
       frac_diat2 = diat2/total,
       frac_dino = dino/total,
       frac_hapt6 = hapt6/total,
       frac_hapt8 = hapt8/total,
       frac_pras = pras/total) %>% 
    select(seascape, hplc_gsfc_id, frac_chloro:frac_pras)
    # select(seascape, frac_chloro:frac_pras) %>%
    # mutate(sum = frac_chloro + frac_crypto + frac_diat1 + frac_diat2 +
    #            frac_dino + frac_hapt6 + frac_hapt8 +
    #            frac_pras + frac_cyano2 + frac_cyano4)
    

# sea_type_avgs2 <- cmtx_sea2 %>%
#     group_by(seascape, season) %>%
#     summarize_at(vars(chloro:pras), mean) %>%
#     mutate(diat = diat1 + diat2,
#            cyano = cyano2 + cyano4,
#            hapt = hapt6 + hapt8,
#            total = chloro + crypto + diat + dino + hapt + pras + cyano) %>%
#     mutate(#year = year,
#              # season = season,
#               #station = station,
#         frac_chloro = chloro/total,
#            frac_crypto = crypto/total,
#            frac_cyano = cyano/total,
#            frac_diat = diat/total,
#            frac_dino = dino/total,
#            frac_hapt = hapt/total,
#            frac_pras = pras/total) %>%
#     select(season, seascape, frac_chloro:frac_pras)

```

```{r}
#making a barplot with PFTs for each season
df_pig <-
    readr::read_csv(paste0(root, "/data/processed/combined_pig_dat.csv")) %>%
    mutate(date_time_utc = replace(
        date_time_utc,
        station == "MR" &
            lubridate::as_date(date_time_utc) == "2018-01-08",
        lubridate::ymd_hms("2018-01-09 00:52:00")
    ))

sea_pft_avgs <- sea_pft %>% 
    left_join(select(df_pig, c(hplc_gsfc_id, tot_chl_a)), by = "hplc_gsfc_id") %>% 
    group_by(seascape) %>% 
    summarise_at(vars(frac_chloro:tot_chl_a), list(avg = mean)) %>% 
    pivot_longer(frac_chloro_avg:frac_pras_avg, names_to = "func_type",
                 names_prefix = "frac_", values_to = "avg_fract") %>% 
    mutate( 
        func_type = gsub("_avg", "", func_type),
        seascape = as.character(seascape),
        seascape = factor(seascape, levels = c("3", "13", "15", "21", "27")))
    
sec2 <- ggh4x::help_secondary(data = sea_pft_avgs,
                      primary = c(seascape, avg_fract),
                      secondary = c(seascape, tot_chl_a_avg),
                      # method = c("range", "max", "fit", "ccf", "sortfit"))
                      method = "max",
                      name = "Average Total Chl-a")

sea_fract_graph <- sea_pft_avgs %>% 
    ggplot(aes(fill = func_type, color = func_type, y=avg_fract, x=seascape)) +
    geom_bar(position = "fill", stat = "identity") +
    theme_classic() +
    theme(text=element_text(family="serif", size = 60),
          axis.title=element_text(size=60),
          legend.position = "bottom",
          legend.direction = "horizontal",
          axis.text.y.right = element_text(color = "chartreuse3"),
          axis.line.y.right = element_line(color = "chartreuse3"),
          axis.title.y.right = element_text(color = "chartreuse3")) +
    labs(x = "Seascape", y= "Proportion to Total Chl-a",
         fill = "Phytoplankton Functional Type",
         color = "Phytoplankton Functional Type") +
    scale_fill_manual(values = Tol_muted) +
    scale_color_manual(values = Tol_muted) +
    geom_point(aes(y = sec$proj(tot_chl_a_avg)), size = 12, color = "chartreuse3", show.legend = F) +
    scale_y_continuous(sec.axis = sec2)

cowplot::save_plot(filename = paste0(root,"/data/plots/phyto_func_type_bar_ratio_seascape", 
           format(Sys.time(), '_%Y%m%d_%H%M%S'),
           ".jpg"), 
          plot = last_plot(),
          base_height = 14,
          base_width = 26,
          dpi = 600, units = "in", device='png')

```


```{r seascape-timeseries-table}

grd <- raster::raster(file.sea[13])
seascapeR::map_ss_grd(grd)
# summarize SeaScape grids into a time series table

seascapeR::plot_ss_ts(seasc_tmser, show_legend = "always")

cowplot::save_plot(filename = paste0(root,"/data/plots/seascape_timeseries", 
           format(Sys.time(), '_%Y%m%d_%H%M%S'),
           ".jpg"), 
          plot = last_plot(),
          base_height = 10,
          base_width = 8,
          dpi = 600, units = "in", device='png')


```







